version: "3"
services: 
  api: 
    container_name: finance_api
    build: .
    image: finance_api
    restart: always
    depends_on:
      - mongo_database
    volumes:
      - ./backend/dist:/usr/backend/dist
      - ./backend/package.json:/usr/backend/package.json
    ports:
      - "3000:3000"
    environment:
        PORT: 3000
        MONGO_HOST: "mongodb://root:root@mongo_database:27017/financeDB"
    networks:
      - connect
    links:
      - mongo_database
    command: npm run start:prod
    
  mongo_database:
    container_name: mongo_database
    image: mongo
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      MONGO_DB: financeDB
    networks:
      - connect
    volumes:
      - ./backend/data:/data/db
    ports: 
      - "27017:27017"

networks:
  connect:
    driver: bridge